### ISSUE TITLE
UnsatisfiedLinkError: cannot locate symbol "SSL_set_mode" referenced by "libunbound.so"

### ISSUE THREAD

**Issue by ehanoc** [gkruja/MoneroTest#1]
Hey man,

I pulled your tree and was trying to get it to run. Do you know how solve this runtime error ?

**Comment by ehanoc** [comment]
Seems to not find the headers files. Do you have the same experience ?

**Comment by ehanoc** [comment]
My device is arm64-v8a, we might be missing the files for that

**Comment by gkruja** [comment]
i only have the armeabi-v7a on the github.

**Comment by ehanoc** [comment]
Do you have instructions on how you built it? I can add the arm64-v8a

**Comment by gkruja** [comment]
would you like to get involved with the project? im trying to make a wallet for core. Im still testing monero on android right now with the ndk

**Comment by ehanoc** [comment]
Yes, definitely.

I've actually forked your project. I'll contribute back with improvements.
Soon as I have some free time I'll have a crack at the 64bit part of things
and the JNI for the wallet api.

I Started looking into this to try and add monero support to my new pet
project :
https://play.google.com/store/apps/details?id=com.bytetobyte.xwallet

But as long as we figure out an working ndk & jni setup... Anybody should
be able to implement monero in Android/java environments.

Cheers

**Comment by gkruja** [comment]
my pr got merged last night ill try and add the libs later today for armv8 so you can start helping me with the project.

**Comment by ehanoc** [comment]
Sounds great man
