### ISSUE TITLE
Support for arm64-v8a

### ISSUE THREAD

**Issue by ehanoc** [gkruja/MoneroTest#2]
Missing. Doesn't run on 64bit devices. 

I can contribute to if this part is set.

**Comment by gkruja** [comment]
I'm working on the 64-bit build now message me on irc when you get a chance to see what part of the workload you can take.

**Comment by ehanoc** [comment]
Is there an issue tracker for this? I'm happy to help out on my free time.

**Comment by gkruja** [comment]
The arm64-v8a failed for me but i have a x86 build so you can use the android emulator ill upload that later.

**Comment by gkruja** [comment]
ill keep working on the arm64-v8a as well as thats something i want to have.

**Comment by gkruja** [comment]
I have added support for arm64-v8a there there is a compilation bug right now with monero and clang on that specific architecture requiring a special compilation flag ill be opening a PR for that and the parsing issue that appears on android when using the shared objects . feel free to contact PM on irc whenever you get a chance if your still interested in working on the project.
