### ISSUE TITLE
Request: a "How to Contribute" and a "License" section in the README

### ISSUE THREAD

**Issue by browep** [gkruja/MoneroTest#3]
I think there is probably a good amount of people that would like to contribute to this repo in one or the other.  A section in the README that outline how to do so would help those people get started.  An a full featured example is here https://github.com/monero-project/monero/blob/master/CONTRIBUTING.md .  But it doesn't have to be that extensive.  Just a section header and a few lines is fine.

For the license, you have lots of options.  I recommend the MIT license https://en.wikipedia.org/wiki/MIT_License .  It's short and sweet and can be summed up with: "use/sell this software however you like, just dont call me if it causes you a problem".

**Comment by gkruja** [comment]
Your right ill start looking into the licensing today and add more info on how to contribute.

**Comment by gkruja** [comment]
if you want you can add the licencing information and ill just merge it on branch.

**Comment by gkruja** [comment]
Just added a small contributing section to the README ill also be updating it as i go.
